In [7]:
import pandas as pd
import numpy as np
from sympy import Point, Circle, atan2, pi
import os
import matplotlib.pyplot as plt

hz = 500 #Kamerans uppdateringsfrekvens
massa_a = 0.0287262
radie_a = 0.0025
massa_b = 0.0281852
radie_b = 0.0025
#OBS mätvärden är i millimeter

#Utifrån tre punkter returnas cirkelns mittpunkt och vinkel över tid
def circle_center(p1, p2, p3):
    center_x = []
    center_y = []
    angle = []
    for e1, e2, e3 in zip(p1,p2,p3):

        d1, d2, d3 = Point(e1[0], e1[1]), Point(e2[0], e2[1]), Point(e3[0], e3[1]) #x,y-pos från varje punkt

        #Bestämmer cirkelns mittpunkt
        p_center = Circle(d1, d2, d3).center
        
        center_x.append(p_center.x.evalf())
        center_y.append(p_center.y.evalf())

        angle_p = atan2(d1.y - p_center.y, d1.x - p_center.x) #Ger värden mellan (-pi,pi)
        
        #Normaliserar värdemängden till [0,2*pi)
        if angle_p < 0:
            angle_p += 2*pi

        angle.append(angle_p.evalf()) #Viktigt, om cirkeln roterar mer än ett varv sparas bara värden mellan [0,2pi]. Spelar egentligen ingen roll iom att enbart vinkelhastighet är relevant senare. (Får utesluta värden sen där derivatan är 2pi vid övergång)
    return (center_x, center_y, angle)


In [ ]:
da

In [8]:
dir = "DATA//raw//del2//friktion//"

#Importera från TSV-filen från QTM
dfa = pd.read_csv(dir+"a_friktion.tsv", delimiter="\t", skiprows=11)
dfb = pd.read_csv(dir+"b_friktion.tsv", delimiter="\t", skiprows=11)

df = pd.concat([dfa,dfb], axis=1)

a1 = np.column_stack((df["a1 X"], df["a1 Y"]))/1000
a2 = np.column_stack((df["a2 X"], df["a2 Y"]))/1000
a3 = np.column_stack((df["a3 X"], df["a3 Y"]))/1000
b1 = np.column_stack((df["b1 X"], df["b1 Y"]))/1000
b2 = np.column_stack((df["b2 X"], df["b2 Y"]))/1000
b3 = np.column_stack((df["b3 X"], df["b3 Y"]))/1000

b1 = b1[:1850]
b2 = b2[:1850]
b3 = b3[:1850]

print(b1)
print(b2)
print(b3)

#Beräkna puckarnas egenskaper
center_a_x, center_a_y, angle_a = circle_center(a1, a2, a3) #För puck A
print("Puck A done")
center_b_x, center_b_y, angle_b = circle_center(b1, b2, b3) #För puck B
print("Puck B done")


dataa = {
    "c_a_x": center_a_x,
    "c_a_y": center_a_y,
    "ang_a": angle_a,
}

pd.DataFrame(dataa).to_csv(dir + "center_a" + ".csv", index=False)
datab = {
    "c_b_x": center_b_x,
    "c_b_y": center_b_y,
    "ang_b": angle_b,
}


pd.DataFrame(datab).to_csv(dir + "center_b" + ".csv", index=False)

[[ 0.273161 -0.168745]
 [ 0.273151 -0.168738]
 [ 0.273151 -0.168738]
 ...
 [ 0.560358 -0.1308  ]
 [ 0.560336 -0.13091 ]
 [ 0.560331 -0.131056]]
[[ 0.293328 -0.201524]
 [ 0.29331  -0.201496]
 [ 0.29331  -0.201494]
 ...
 [ 0.524777 -0.116099]
 [ 0.524673 -0.116451]
 [ 0.524534 -0.116785]]
[[ 0.310322 -0.161103]
 [ 0.310321 -0.161089]
 [ 0.310313 -0.161088]
 ...
 [ 0.534787 -0.15858 ]
 [ 0.535021 -0.158964]
 [ 0.535184 -0.159273]]
Puck A done
Puck B done
